language: node_js
node_js:
  - 12.14.1
cashe:
  directories:
    - node_modules

install:
  - yarn ci
script:
  - yarn test
  - yarn build
  - yarn lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
  branch: master
